name: Linting and Tests

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          show-progress: false

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version-file: ./go.mod

      - name: Set up golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest

      - name: Install dependencies
        run: go mod download

      - name: Run vet
        run: go vet ./...

      - name: Run linter
        run: golangci-lint run ./...

      - name: Run tests
        run: go test -v ./...
